#!/usr/bin/env ruby
puts '=> Loading Rails...'

require File.dirname(__FILE__) + '/config/environment'

MailerService::Application.config.allow_concurrency = true

workling = File.join(File.dirname(__FILE__), 'vendor', 'plugins', 'workling', 'script', 'listen.rb')
options = {
  :app_name   => "workling",
  :ARGV       => ARGV,
  :dir_mode   => :normal,
  :dir        => File.join(File.dirname(__FILE__), 'log'),
  # :dir        => File.join(File.dirname(__FILE__), '..', 'log'),
  :log_output => true,
  :multiple   => false,
  :backtrace  => true,
  :monitor    => true
}

Daemons.run(workling, options)
